{"name": "test_login_failure_b", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <test001.test_allure.TestLogin object at 0x0000000003948A20>\n\n    @allure.story(\"密码缺失\")\n    def test_login_failure_b(self):\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录之后登录失败\"):\n>           assert \"1\" == 1\nE           AssertionError: assert '1' == 1\n\ntest_allure.py:22: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1588735924726, "stop": 1588735924727}, {"name": "点击密码", "status": "passed", "start": 1588735924727, "stop": 1588735924727}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"D:\\PyCharm 5.0.4\\untitled\\test001\\test_allure.py\", line 22, in test_login_failure_b\n    assert \"1\" == 1\n"}, "start": 1588735924727, "stop": 1588735924728}], "attachments": [{"name": "stdout", "source": "ff4d15b6-b4f7-4d9c-b265-650027370576-attachment.txt", "type": "text/plain"}], "start": 1588735924726, "stop": 1588735924729, "uuid": "02c1465e-5332-40f7-8659-4285efcfc279", "historyId": "bc79afb9bb82db5ef87657e919529110", "testCaseId": "f7e25e4ad216d3428c150cc95f925473", "fullName": "test_allure.TestLogin#test_login_failure_b", "labels": [{"name": "story", "value": "密码缺失"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_allure"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PC201207261052"}, {"name": "thread", "value": "8536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}